<a href="https://colab.research.google.com/github/MarcinBitowt/data-science/blob/master/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print('hello')

hello


In [4]:
import numpy as np
np.version

<module 'numpy.version' from '/usr/local/lib/python3.6/dist-packages/numpy/version.py'>

In [0]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [0]:
np.full(shape=(3,3),fill_value=2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [0]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
A.reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [0]:
A * B

array([ 9, -1, 12,  4])

In [0]:
c = np.random.randint(5)
print(c)

2


In [0]:
np.exp(1)

2.718281828459045

In [0]:
np.sqrt(9)

3.0

In [0]:
bool(0)

False

In [0]:
A = np.random.rand(5)
A

array([0.26581912, 0.28468588, 0.25358821, 0.32756395, 0.1441643 ])

In [0]:
np.argmax(A)

3

In [0]:
A[np.argmax(A)]

0.3275639476887341

In [0]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
A[2]

2

In [0]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [0]:
A[[0,2]]

array([0, 2])

In [0]:
A[-2]

18

In [7]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [8]:
np.linalg.norm(v1)

4.123105625617661

In [9]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

In [10]:
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(p-q)

5.0

In [11]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

In [14]:
x = np.array([[5,3],[3,9]])
y = np.array([[1],[-1]])
print(x,'\n')
print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [15]:
z = np.dot(x,y)
z

array([[ 2],
       [-6]])

In [16]:
x = np.array([[2,-1,3],[3,1,0]])
y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])
print(x,'\n')
print(y)


[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [17]:
 z = np.dot(x,y)
 z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [18]:
 A = np.array([[2,4],[-1,3]])
 np.linalg.det(A)

9.999999999999998

In [19]:
np.trace(A)

5

In [20]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
A


array([[ 2,  4],
       [-1,  3]])

In [0]:
B = np.linalg.inv(A)

In [23]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [24]:
np.transpose(A);
A

array([[ 2,  4],
       [-1,  3]])

In [26]:

# 2x +4y = 10
# x - y = -1
A = np.array([[2,4],[1,-1]]) # macierz niewiadomych
B = np.array([[10],[-1]]) # macierz wyrazow wolnych

print(A,'\n',B)

A_inv = np.linalg.inv(A) # odwrocenie macierzy niewiadomych
X = np.dot(A_inv,B) # mnozenie odwroconej macierzy niewiadomych z macierza wyrazow wolnych
print(X)


[[ 2  4]
 [ 1 -1]] 
 [[10]
 [-1]]
[[1.]
 [2.]]
