<a href="https://colab.research.google.com/github/MarcinBitowt/data-science/blob/master/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
print('hello')

hello


In [3]:
import numpy as np
np.version

<module 'numpy.version' from '/usr/local/lib/python3.6/dist-packages/numpy/version.py'>

In [6]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
np.full(shape=(3,3),fill_value=2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [8]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
A.reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [19]:
A * B

array([ 9, -1, 12,  4])

In [28]:
c = np.random.randint(5)
print(c)

2


In [29]:
np.exp(1)

2.718281828459045

In [30]:
np.sqrt(9)

3.0

In [32]:
bool(0)

False

In [34]:
A = np.random.rand(5)
A

array([0.26581912, 0.28468588, 0.25358821, 0.32756395, 0.1441643 ])

In [35]:
np.argmax(A)

3

In [36]:
A[np.argmax(A)]

0.3275639476887341

In [37]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
A[2]

2

In [39]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [42]:
A[[0,2]]

array([0, 2])

In [44]:
A[-2]

18